### ISSUE TITLE
Not threadsafe

### ISSUE THREAD

**Issue by jpillora** [GianlucaGuarini/go-observable#2]
Should use the sync package to allow concurrent access to internal data structures

**Comment by GianlucaGuarini** [comment]
Yes you are right, I am not yet sure if I want to use the RWMutex or just to get rid of the goroutines and the whole async strategy. Any pull request (with tests) is welcome ;)

**Comment by GianlucaGuarini** [comment]
I want also to benchmark the 2 strategies async vs sync

**Comment by jpillora** [comment]
Sync could work, users could make triggers async with `go o.Trigger(...)`. I guess there's an issue of each event would trigger in series. Another option is `o.GoTrigger(...)`, which internally would call each callback in it's own goroutine.

RE: Performance: I think just go with a Mutex for now, modifying a map and unlocking is much faster than any use of reflect, so I don't think it will matter too much at this point.

**Comment by GianlucaGuarini** [comment]
thanks for the hint I will come back here asap without changing tha API of the script

**Comment by GianlucaGuarini** [comment]
the new version should be thread safe.. can you please have a look?

**Comment by jpillora** [comment]
Still appears to have possible races. Every instance in the code which performs a write (e.g. `o.Callbacks[event] = ...`) could possibly be run concurrently should be protected with a sync lock.

**Comment by GianlucaGuarini** [comment]
But running `go test -race` there are no errors traced anymore. Can you provide an example I could test where there could be a race condition?

**Comment by jpillora** [comment]
I don't actually use go test -race much, though I probably should. I just
think about which code paths which could possibly be run by multiple CPUs
at once. I probably should use go test -race more...

**Comment by GianlucaGuarini** [comment]
this issue was solved with https://github.com/GianlucaGuarini/go-observable/commit/0ca0cebdbcf74eb2c2a849833cddb563f14519a6 thank you for your help
